apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{app_name}}
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: {{app_name}}
    spec:
      volumes:
        - name: spanner-creds
          secret:
            secretName: spanner-creds
      containers:
        - name: {{app_name}}
          image: {{image_name}}
          imagePullPolicy: Always
          env:
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: /secrets/app-with-secrets/spanner-cred.json
          volumeMounts:
            - name: spanner-creds
              mountPath: /secrets/app-with-secrets
              readOnly: true
---
kind: Service
apiVersion: v1
metadata:
  name: {{app_name}}
spec:
  selector:
    app: {{app_name}}
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
  type: LoadBalancer
  loadBalancerSourceRanges:
  - 151.140.0.0/16
  - 165.130.0.0/16
  - 207.11.0.0/17
  - 50.207.27.182/32
  - 98.6.11.8/29